---
exclude: "(venv|.vscode)" # regex
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        args: ["--print-width=135"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: ["--target-version", "py39"]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: \..*ignore
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
        args: ["server/requirements.in", "server/requirements.txt", "worker/requirements.in", "worker/requirements.txt"]

      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        exclude_types: [makefile, binary]
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: 3df2cd5fc0bffe63b0a5e0021f9885a223d51600
    hooks:
      - id: CVE-2017-18342
      - id: remove-en-dashes
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
      - id: remove-unicode-zero-width-space
