version: "3.3"
services:
  redis:
    image: redis
  server:
    build: server
    image: upside-down-server
    environment:
      - REDIS_HOST=redis
      - SERVER_KEY=hunter2
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
  worker:
    build: worker
    image: upside-down-worker
    privileged: true
    environment:
      - SERVER_HOST=server:5000
      - SERVER_KEY=hunter2
