apiVersion: v1
kind: Service
metadata:
  name: stranger-things-lights-redis
  labels:
    app: stranger-things-lights
spec:
  ports:
    - port: 6379
  selector:
    app: stranger-things-lights
    tier: redis
